/*
 * ns_tasks.c -- Non-Secure FreeRTOS task implementations
 *
 * Lab 08 -- TrustZone-M: Secure/Non-Secure Partition
 * Platform: NXP FRDM-MCXN236 (Cortex-M33 @ 150 MHz, Non-Secure)
 *
 * Build note: link against cmse_implib.o (generated by the Secure project)
 *   so that Secure_ADC_Read / Secure_ADC_Init resolve to SG veneers.
 */

#include "FreeRTOS.h"
#include "task.h"
#include "MCXN236.h"        /* DWT registers */
#include "fsl_debug_console.h"
#include "secure_api.h"     /* NSC declarations -- resolved via cmse_implib.o */
#include "ns_tasks.h"

/* ── DWT helpers (reuse from Lab 06) ─────────────────────────────────────── */
static uint32_t _dwt_start;
static uint32_t _dwt_elapsed;

static inline void DWT_Enable(void)
{
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT       = 0;
    DWT->CTRL        |= DWT_CTRL_CYCCNTENA_Msk;
}

#define DWT_START()  do { _dwt_start = DWT->CYCCNT; } while (0)
#define DWT_STOP()   do { _dwt_elapsed = DWT->CYCCNT - _dwt_start; } while (0)

/* ── ns_dummy_adc_read ───────────────────────────────────────────────────── */
/*
 * Pure NS function with identical logic to Secure_ADC_Read.
 * Used as the baseline in vBenchmarkTask (Part D) so the only difference
 * is the S/NS boundary crossing overhead.
 */
static volatile int32_t s_ns_adc = 0;

int32_t ns_dummy_adc_read(void)
{
    s_ns_adc = (s_ns_adc + 37) % 4096;
    return s_ns_adc;
}

/* ── vSensorTask ─────────────────────────────────────────────────────────── */
/*
 * Part B: calls Secure_ADC_Init once, then Secure_ADC_Read every 200 ms.
 *
 * Part C (deliberate fault -- COMMENT OUT after observing the SecureFault):
 *   Uncomment the block below to attempt a direct NS read of Secure SRAM.
 *   Expected result: SecureFault_Handler fires, printing SFSR/SFAR.
 */
void vSensorTask(void *pv)
{
    /* TODO (Part B): call Secure_ADC_Init via NSC veneer */
    Secure_ADC_Init();

    for (;;) {
        /* TODO (Part B): read ADC value via NSC veneer and print it */
        int32_t value = Secure_ADC_Read();
        PRINTF("[NS] ADC value = %ld\r\n", (long)value);

        /* ------------------------------------------------------------------ *
         * Part C: DELIBERATE SECUREFAULT -- uncomment to test                *
         * ------------------------------------------------------------------ *
         * volatile uint32_t *secure_ptr =                                    *
         *     (volatile uint32_t *)0x20010000U;  <- Secure SRAM              *
         * uint32_t val = *secure_ptr;   <- triggers SecureFault              *
         * PRINTF("[NS] should never print: %lu\r\n", (unsigned long)val);*
         * ------------------------------------------------------------------ */

        vTaskDelay(pdMS_TO_TICKS(200));
    }
}

/* ── vBenchmarkTask ──────────────────────────────────────────────────────── */
/*
 * Part D: benchmark NSC call overhead vs a direct NS call.
 *
 * Expected output example (values depend on pipeline):
 *   [BENCH] NSC: 48 cycles  Direct: 6 cycles  Overhead: 42 cycles
 *
 * At 150 MHz: 42 cycles = 280 ns.  Acceptable for 1 kHz (1 ms period).
 *
 * TODO: adjust WARMUP_RUNS if the first measurement is inconsistent due to
 *       I-cache cold start.
 */
#define WARMUP_RUNS  3

void vBenchmarkTask(void *pv)
{
    /* TODO: initialise DWT cycle counter */
    DWT_Enable();

    /* Warm-up: run both functions a few times to fill I-cache */
    for (int w = 0; w < WARMUP_RUNS; w++) {
        volatile int32_t tmp = Secure_ADC_Read();
        tmp = ns_dummy_adc_read();
        (void)tmp;
    }

    uint32_t nsc_cycles    = 0;
    uint32_t direct_cycles = 0;

    /* ── Measure NSC call ──────────────────────────────────────────────── */
    /* TODO: wrap Secure_ADC_Read() with DWT_START / DWT_STOP */
    DWT_START();
    volatile int32_t v1 = Secure_ADC_Read();   /* crosses S/NS boundary */
    DWT_STOP();
    nsc_cycles = _dwt_elapsed;
    (void)v1;

    /* ── Measure direct NS call ─────────────────────────────────────────── */
    /* TODO: wrap ns_dummy_adc_read() with DWT_START / DWT_STOP */
    DWT_START();
    volatile int32_t v2 = ns_dummy_adc_read();
    DWT_STOP();
    direct_cycles = _dwt_elapsed;
    (void)v2;

    /* ── Print results ──────────────────────────────────────────────────── */
    PRINTF("[BENCH] NSC call: %lu cycles  Direct: %lu cycles  Overhead: %lu cycles\r\n",
                (unsigned long)nsc_cycles,
                (unsigned long)direct_cycles,
                (unsigned long)(nsc_cycles - direct_cycles));

    /* TODO (Question D1): convert overhead cycles to nanoseconds at 150 MHz */
    /* TODO (Question D2): describe where the FreeRTOS Secure context is stored */

    vTaskDelete(NULL);
}
